### ISSUE TITLE
Setup Postgres integration

### ISSUE THREAD

**Issue by christoff-linde** [christoff-linde/pih-rs#4]
## Description

This would integrate a PostgreSQL database into the backend API.

Initial research indicates the following as best options (in terms of crates, etc.):
- sqlx
- pgsql

Also, due to the nature of the data gathered, a timeseries database extension to Postgres could be beneficial, as it is optimised better for timeseries data.

## Task List

- [x] Integrate sqlx crate
- [x] Setup DB connections & test query
- [x] Setup Docker to include setup for DB
